version: "3"

services:
  apache:
    build:
      context: ./
      dockerfile: ./docker/apache/Dockerfile
    volumes:
      - ./src:/var/www:cached
    working_dir: /var/www
    restart: unless-stopped
    ports:
      - ${APACHE_PORT}:80
    environment:
      - SERVICE_NAME=apache
      - SERVICE_TAGS=dev
    networks:
      - network
  mysql:
    image: mysql:8.0
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - mysql:/var/lib/mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SERVICE_NAME=mysql
      - SERVICE_TAGS=dev
    networks:
      - network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
    networks:
      - network
  mail:
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_PORT}:8025
    networks:
      - network

networks:
  network:
    driver: bridge
volumes:
  mysql:
